image: Visual Studio 2022
configuration: Release
platform:
- Win32
- x64
environment:
  DXSDK: '%DXSDK_DIR%'
  BOOST_1_71_0: 'C:\Libraries\boost_1_89_0'
before_build:
- cmd: >-
    set CI=1

    for /f "tokens=1-3 delims=-" %%i in ('git describe --always --tags') do (set GIT_LAST_TAG=%%i&set GIT_COMMIT_HASH=%%k)

    for /f %%i in ('git rev-list --count HEAD') do set GIT_COMMITS_COUNT=%%i

    set CI_VERSION=%GIT_LAST_TAG%.%GIT_COMMITS_COUNT%-%GIT_COMMIT_HASH%

    echo %CI_VERSION%

    echo %PLATFORM%

    echo %CONFIGURATION%

    echo cop_%GIT_LAST_TAG%_%PLATFORM%.7z
build:
  project: ./engine.sln
  verbosity: minimal
after_build:
- cmd: >-
    set COR_PLAT=%PLATFORM%

    IF "%COR_PLAT%" == "Win32" set COR_PLAT=x86

    set BUGTRAP=BugTrap-%COR_PLAT%.dll

    IF "%COR_PLAT%" == "x86" set BUGTRAP=BugTrap.dll

    md dist

    echo ===================== engine files =====================

    md dist\engine

    copy opt\start_%COR_PLAT%.bat dist\engine

    md dist\engine\bin_%COR_PLAT%

    copy intermediate\%PLATFORM%-%CONFIGURATION%\*.exe dist\engine\bin_%COR_PLAT%\

    copy intermediate\%PLATFORM%-%CONFIGURATION%\*.dll dist\engine\bin_%COR_PLAT%\

    copy intermediate\%PLATFORM%-%CONFIGURATION%\*.pdb dist\engine\bin_%COR_PLAT%\

    copy SDK\binaries\%COR_PLAT%\lua51.dll dist\engine\bin_%COR_PLAT%\

    md dist\engine\bin_%COR_PLAT%\lua\jit

    copy SDK\binaries\%COR_PLAT%\lua\jit\* dist\engine\bin_%COR_PLAT%\lua\jit\

    copy SDK\binaries\%COR_PLAT%\%BUGTRAP% dist\engine\bin_%COR_PLAT%\

    md dist\engine\gamedata\scripts

    copy gamedata\scripts\* dist\engine\gamedata\scripts\

    7z a cop_%GIT_LAST_TAG%_%COR_PLAT%.7z dist\engine\*
artifacts:
- path: .\cop_$(git_last_tag)_$(cor_plat).7z
  name: release
deploy:
- provider: GitHub
  auth_token:
    secure: hIR+pkYuyGXqvV8K4MrSkwHkugMQtY33//LaDnCcoiR28X62+qW6AVbm/P/y3gAn
  artifact: release
  on:
    appveyor_repo_tag: true
